ratings:
  namespace: bookinfo-prd
  image: asia.gcr.io/kubenetes-446214/bookinfo-ratings
  tag: prd
  replicas: 1
  imagePullSecrets: registry-bookinfo
  port: 9080
  healthCheckPath: "/health"
  mongodbPasswordExistingSecret: bookinfo-prd-ratings-mongodb-secret
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  host: 34.142.177.239.nip.io
  path: "/ratings(/|$)(.*)"
  serviceType: ClusterIP
extraEnv:
  SERVICE_VERSION: v2
  MONGO_DB_URL: mongodb://bookinfo-prd-ratings-mongodb:27017/ratings-prd
  MONGO_DB_USERNAME: ratings-prd